import time

print('This is a test deployment file')
print('')
print('This execution does not actually do anything')
print('It just simulates a real execution of a deployment file')
print('')

print('Build and Test phases were successful')
print('Beginning deployment of application to staging environment')
time.sleep(3)
print('')
print('Searching for target host')
time.sleep(1)
print('Target host found. Commencing deployment')
print('Directory created. Moving files...')
time.sleep(5)
print('Files successfully moved to target')
print('Launching API Server...')
time.sleep(5)
print('Server launched, Number of warnings encountered: 0')
print('Initiating Health Check')
time.sleep(2)
print('Health check successful, all functions working as expected')
print('Checking success conditions...')
print('Deployment successful!')
print('')
